realpath() of walry.ini failed: No such file or directory [core/utils.c line 3618]
[uWSGI] getting INI configuration from walry.ini
*** Starting uWSGI 2.0.15 (64bit) on [Sun Sep 17 15:03:51 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 28 June 2017 16:53:37
os: Linux-3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
nodename: izuf6e0xn290ligau0r66qz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mahl/projects/django/walry
detected binary path: /usr/bin/uwsgi
chdir() to /home/mahl/projects/django/walry/walry/
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8181 fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1551f50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added ../ to pythonpath.
Traceback (most recent call last):
  File "../django_wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/lib64/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/lib64/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib64/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/lib64/python2.7/site-packages/django/apps/config.py", line 120, in create
    mod = import_module(mod_path)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named django_admin_bootstrappeddjango.contrib
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 25750)
spawned uWSGI worker 1 (pid: 25755, cores: 1)
spawned uWSGI worker 2 (pid: 25756, cores: 1)
[uWSGI] getting INI configuration from walry.ini
*** Starting uWSGI 2.0.15 (64bit) on [Sun Sep 17 15:05:15 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 28 June 2017 16:53:37
os: Linux-3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
nodename: izuf6e0xn290ligau0r66qz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mahl/projects/django/walry
detected binary path: /usr/bin/uwsgi
chdir() to /home/mahl/projects/django/walry/walry/
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8181 fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x204ef50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added ../ to pythonpath.
Traceback (most recent call last):
  File "../django_wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/usr/lib64/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/lib64/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib64/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/lib64/python2.7/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named crispy_forms
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 25838)
spawned uWSGI worker 1 (pid: 25843, cores: 1)
spawned uWSGI worker 2 (pid: 25844, cores: 1)
[uWSGI] getting INI configuration from walry.ini
*** Starting uWSGI 2.0.15 (64bit) on [Sun Sep 17 15:06:24 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 28 June 2017 16:53:37
os: Linux-3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
nodename: izuf6e0xn290ligau0r66qz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mahl/projects/django/walry
detected binary path: /usr/bin/uwsgi
chdir() to /home/mahl/projects/django/walry/walry/
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8181 fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x184ff50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added ../ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x184ff50 pid: 25896 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 25896)
spawned uWSGI worker 1 (pid: 25901, cores: 1)
spawned uWSGI worker 2 (pid: 25902, cores: 1)
Invalid HTTP_HOST header: 'hust.walry.top'. You may need to add u'hust.walry.top' to ALLOWED_HOSTS.
[pid: 25901|app: 0|req: 1/1] 125.121.39.215 () {40 vars in 698 bytes} [Sun Sep 17 07:06:54 2017] GET /weixin/ => generated 55730 bytes in 61 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from walry.ini
*** Starting uWSGI 2.0.15 (64bit) on [Sun Sep 17 15:07:47 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 28 June 2017 16:53:37
os: Linux-3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
nodename: izuf6e0xn290ligau0r66qz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mahl/projects/django/walry
detected binary path: /usr/bin/uwsgi
chdir() to /home/mahl/projects/django/walry/walry/
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8181 fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1266f50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added ../ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1266f50 pid: 25953 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 25953)
spawned uWSGI worker 1 (pid: 25958, cores: 1)
spawned uWSGI worker 2 (pid: 25959, cores: 1)
Internal Server Error: /weixin/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/lib64/python2.7/site-packages/django/urls/resolvers.py", line 362, in resolve
    for pattern in self.url_patterns:
  File "/usr/lib64/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib64/python2.7/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib64/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib64/python2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "../walry/urls.py", line 22, in <module>
    url(r'^weixin/',include("weixin.urls")),
  File "/usr/lib64/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "../weixin/urls.py", line 3, in <module>
    from . import views
  File "../weixin/views.py", line 18
SyntaxError: Non-ASCII character '\xe6' in file ../weixin/views.py on line 18, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
[pid: 25959|app: 0|req: 1/1] 125.121.39.215 () {42 vars in 729 bytes} [Sun Sep 17 07:07:52 2017] GET /weixin/ => generated 94598 bytes in 87 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from walry.ini
*** Starting uWSGI 2.0.15 (64bit) on [Sun Sep 17 15:09:58 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 28 June 2017 16:53:37
os: Linux-3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
nodename: izuf6e0xn290ligau0r66qz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mahl/projects/django/walry
detected binary path: /usr/bin/uwsgi
chdir() to /home/mahl/projects/django/walry/walry/
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8181 fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1998f50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added ../ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1998f50 pid: 26015 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 26015)
spawned uWSGI worker 1 (pid: 26020, cores: 1)
spawned uWSGI worker 2 (pid: 26021, cores: 1)
Not Found: /weixin/
[pid: 26021|app: 0|req: 1/1] 125.121.39.215 () {42 vars in 729 bytes} [Sun Sep 17 07:10:03 2017] GET /weixin/ => generated 2131 bytes in 120 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Internal Server Error: /weixin/findTask/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "../weixin/views.py", line 8, in find_task
    user_id = request.POST["uid"]
  File "/usr/lib64/python2.7/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'uid'"
[pid: 26021|app: 0|req: 2/2] 125.121.39.215 () {40 vars in 716 bytes} [Sun Sep 17 07:10:11 2017] GET /weixin/findTask/ => generated 61624 bytes in 53 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from walry.ini
*** Starting uWSGI 2.0.15 (64bit) on [Sun Sep 17 16:37:02 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 28 June 2017 16:53:37
os: Linux-3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
nodename: izuf6e0xn290ligau0r66qz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mahl/projects/django/walry
detected binary path: /usr/bin/uwsgi
chdir() to /home/mahl/projects/django/walry/walry/
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8181 fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x16bbf50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added ../ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x16bbf50 pid: 26579 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 26579)
spawned uWSGI worker 1 (pid: 26584, cores: 1)
spawned uWSGI worker 2 (pid: 26585, cores: 1)
Internal Server Error: /weixin/findTask/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "../weixin/views.py", line 24, in find_task
    return render(request, 'findTask.html')
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: findTask.html
[pid: 26584|app: 0|req: 1/1] 125.121.39.215 () {42 vars in 747 bytes} [Sun Sep 17 08:37:10 2017] GET /weixin/findTask/ => generated 71135 bytes in 96 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
Internal Server Error: /weixin/findTask/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "../weixin/views.py", line 24, in find_task
    return render(request, 'findTask.html')
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: findTask.html
[pid: 26584|app: 0|req: 2/2] 125.121.39.215 () {42 vars in 747 bytes} [Sun Sep 17 08:37:16 2017] GET /weixin/findTask/ => generated 71135 bytes in 57 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
Internal Server Error: /weixin/findTask/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "../weixin/views.py", line 24, in find_task
    return render(request, 'findTask.html')
  File "/usr/lib64/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib64/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: findTask.html
[pid: 26584|app: 0|req: 3/3] 125.121.39.215 () {42 vars in 747 bytes} [Sun Sep 17 08:37:49 2017] GET /weixin/findTask/ => generated 71135 bytes in 54 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from walry.ini
*** Starting uWSGI 2.0.15 (64bit) on [Sun Sep 17 16:41:19 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 28 June 2017 16:53:37
os: Linux-3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
nodename: izuf6e0xn290ligau0r66qz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mahl/projects/django/walry
detected binary path: /usr/bin/uwsgi
chdir() to /home/mahl/projects/django/walry/walry/
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8181 fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1992f50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added ../ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1992f50 pid: 26654 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 26654)
spawned uWSGI worker 1 (pid: 26659, cores: 1)
spawned uWSGI worker 2 (pid: 26660, cores: 1)
[pid: 26660|app: 0|req: 1/1] 125.121.39.215 () {42 vars in 747 bytes} [Sun Sep 17 08:41:24 2017] GET /weixin/findTask/ => generated 455 bytes in 23 msecs (HTTP/1.1 200) 5 headers in 277 bytes (1 switches on core 0)
[pid: 26660|app: 0|req: 2/2] 125.121.39.215 () {52 vars in 1041 bytes} [Sun Sep 17 08:41:50 2017] POST /weixin/findTask/ => generated 455 bytes in 50 msecs (HTTP/1.1 200) 5 headers in 277 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from walry.ini
*** Starting uWSGI 2.0.15 (64bit) on [Sun Sep 17 16:48:09 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 28 June 2017 16:53:37
os: Linux-3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
nodename: izuf6e0xn290ligau0r66qz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mahl/projects/django/walry
detected binary path: /usr/bin/uwsgi
chdir() to /home/mahl/projects/django/walry/walry/
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8181 fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x167af50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added ../ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x167af50 pid: 26737 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 26737)
spawned uWSGI worker 1 (pid: 26742, cores: 1)
spawned uWSGI worker 2 (pid: 26743, cores: 1)
[pid: 26742|app: 0|req: 1/1] 125.121.39.215 () {52 vars in 1041 bytes} [Sun Sep 17 08:48:20 2017] POST /weixin/findTask/ => generated 1907 bytes in 67 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 26742|app: 0|req: 2/2] 125.121.39.215 () {52 vars in 1041 bytes} [Sun Sep 17 08:48:35 2017] POST /weixin/findTask/ => generated 1907 bytes in 36 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 26742|app: 0|req: 3/3] 125.121.39.215 () {44 vars in 836 bytes} [Sun Sep 17 08:48:47 2017] GET /weixin/findTask/ => generated 766 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 277 bytes (1 switches on core 0)
[pid: 26742|app: 0|req: 4/4] 125.121.39.215 () {52 vars in 1041 bytes} [Sun Sep 17 08:48:51 2017] POST /weixin/findTask/ => generated 1907 bytes in 45 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from walry.ini
*** Starting uWSGI 2.0.15 (64bit) on [Sun Sep 17 16:53:54 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 28 June 2017 16:53:37
os: Linux-3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
nodename: izuf6e0xn290ligau0r66qz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mahl/projects/django/walry
detected binary path: /usr/bin/uwsgi
chdir() to /home/mahl/projects/django/walry/walry/
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8181 fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xf1ef50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added ../ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xf1ef50 pid: 26869 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 26869)
spawned uWSGI worker 1 (pid: 26874, cores: 1)
spawned uWSGI worker 2 (pid: 26875, cores: 1)
[pid: 26875|app: 0|req: 1/1] 125.121.39.215 () {44 vars in 836 bytes} [Sun Sep 17 08:54:03 2017] GET /weixin/findTask/ => generated 766 bytes in 23 msecs (HTTP/1.1 200) 5 headers in 277 bytes (1 switches on core 0)
[pid: 26875|app: 0|req: 2/2] 125.121.39.215 () {52 vars in 1041 bytes} [Sun Sep 17 08:54:14 2017] POST /weixin/findTask/ => generated 1856 bytes in 48 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from walry.ini
*** Starting uWSGI 2.0.15 (64bit) on [Sun Sep 17 16:55:09 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 28 June 2017 16:53:37
os: Linux-3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
nodename: izuf6e0xn290ligau0r66qz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mahl/projects/django/walry
detected binary path: /usr/bin/uwsgi
chdir() to /home/mahl/projects/django/walry/walry/
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8181 fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x15d1f50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added ../ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x15d1f50 pid: 26928 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 26928)
spawned uWSGI worker 1 (pid: 26933, cores: 1)
spawned uWSGI worker 2 (pid: 26934, cores: 1)
[pid: 26934|app: 0|req: 1/1] 125.121.39.215 () {52 vars in 1041 bytes} [Sun Sep 17 08:55:19 2017] POST /weixin/findTask/ => generated 1871 bytes in 74 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 26934|app: 0|req: 2/2] 125.121.39.215 () {42 vars in 805 bytes} [Sun Sep 17 08:55:31 2017] GET /weixin/findTask/ => generated 766 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 277 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from walry.ini
*** Starting uWSGI 2.0.15 (64bit) on [Sun Sep 17 18:46:30 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 28 June 2017 16:53:37
os: Linux-3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
nodename: izuf6e0xn290ligau0r66qz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mahl/projects/django/walry
detected binary path: /usr/bin/uwsgi
chdir() to /home/mahl/projects/django/walry/walry/
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8181 fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x112bf50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added ../ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x112bf50 pid: 27637 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 27637)
spawned uWSGI worker 1 (pid: 27642, cores: 1)
spawned uWSGI worker 2 (pid: 27643, cores: 1)
[pid: 27642|app: 0|req: 1/1] 125.121.39.215 () {52 vars in 1041 bytes} [Sun Sep 17 10:46:39 2017] POST /weixin/findTask/ => generated 2544 bytes in 68 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 27642|app: 0|req: 2/2] 125.121.39.215 () {44 vars in 836 bytes} [Sun Sep 17 10:46:44 2017] GET /weixin/findTask/ => generated 1089 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 27642|app: 0|req: 3/3] 125.121.39.215 () {52 vars in 1041 bytes} [Sun Sep 17 10:46:53 2017] POST /weixin/findTask/ => generated 2544 bytes in 44 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from walry.ini
*** Starting uWSGI 2.0.15 (64bit) on [Sun Sep 17 18:50:06 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 28 June 2017 16:53:37
os: Linux-3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
nodename: izuf6e0xn290ligau0r66qz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mahl/projects/django/walry
detected binary path: /usr/bin/uwsgi
chdir() to /home/mahl/projects/django/walry/walry/
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8181 fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1f86f50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added ../ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1f86f50 pid: 27713 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 27713)
spawned uWSGI worker 1 (pid: 27719, cores: 1)
spawned uWSGI worker 2 (pid: 27720, cores: 1)
[pid: 27720|app: 0|req: 1/1] 125.121.39.215 () {52 vars in 1055 bytes} [Sun Sep 17 10:50:11 2017] POST /weixin/findTask/ => generated 2965 bytes in 64 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 27720|app: 0|req: 2/2] 125.121.39.215 () {52 vars in 1041 bytes} [Sun Sep 17 10:50:27 2017] POST /weixin/findTask/ => generated 29194 bytes in 80 msecs (HTTP/1.1 200) 5 headers in 279 bytes (1 switches on core 0)
[pid: 27720|app: 0|req: 3/3] 125.121.39.215 () {52 vars in 1041 bytes} [Sun Sep 17 10:50:44 2017] POST /weixin/findTask/ => generated 2965 bytes in 40 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 27720|app: 0|req: 4/4] 125.121.39.215 () {52 vars in 1055 bytes} [Sun Sep 17 10:51:19 2017] POST /weixin/findTask/ => generated 2965 bytes in 43 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from walry.ini
*** Starting uWSGI 2.0.15 (64bit) on [Sun Sep 17 18:55:04 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 28 June 2017 16:53:37
os: Linux-3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
nodename: izuf6e0xn290ligau0r66qz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mahl/projects/django/walry
detected binary path: /usr/bin/uwsgi
chdir() to /home/mahl/projects/django/walry/walry/
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8181 fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1043f50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added ../ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1043f50 pid: 27806 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 27806)
spawned uWSGI worker 1 (pid: 27811, cores: 1)
spawned uWSGI worker 2 (pid: 27812, cores: 1)
[pid: 27811|app: 0|req: 1/1] 125.121.39.215 () {52 vars in 1055 bytes} [Sun Sep 17 10:55:10 2017] POST /weixin/findTask/ => generated 2970 bytes in 57 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from walry.ini
*** Starting uWSGI 2.0.15 (64bit) on [Sun Sep 17 18:56:34 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 28 June 2017 16:53:37
os: Linux-3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
nodename: izuf6e0xn290ligau0r66qz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mahl/projects/django/walry
detected binary path: /usr/bin/uwsgi
chdir() to /home/mahl/projects/django/walry/walry/
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8181 fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x16c8f50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added ../ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x16c8f50 pid: 27878 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 27878)
spawned uWSGI worker 1 (pid: 27883, cores: 1)
spawned uWSGI worker 2 (pid: 27884, cores: 1)
[pid: 27884|app: 0|req: 1/1] 125.121.39.215 () {52 vars in 1055 bytes} [Sun Sep 17 10:56:39 2017] POST /weixin/findTask/ => generated 2973 bytes in 70 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
Internal Server Error: /weixin/deleteTask/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "../weixin/views.py", line 35, in delete_task
    task = cursor.fetone()
AttributeError: 'DictCursor' object has no attribute 'fetone'
[pid: 27884|app: 0|req: 2/2] 125.121.39.215 () {44 vars in 849 bytes} [Sun Sep 17 10:56:41 2017] GET /weixin/deleteTask/?id= => generated 12422 bytes in 47 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from walry.ini
*** Starting uWSGI 2.0.15 (64bit) on [Sun Sep 17 18:58:59 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 28 June 2017 16:53:37
os: Linux-3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
nodename: izuf6e0xn290ligau0r66qz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mahl/projects/django/walry
detected binary path: /usr/bin/uwsgi
chdir() to /home/mahl/projects/django/walry/walry/
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8181 fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1c64f50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added ../ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1c64f50 pid: 27941 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 27941)
spawned uWSGI worker 1 (pid: 27946, cores: 1)
spawned uWSGI worker 2 (pid: 27947, cores: 1)
[pid: 27946|app: 0|req: 1/1] 125.121.39.215 () {52 vars in 1055 bytes} [Sun Sep 17 10:59:07 2017] POST /weixin/findTask/ => generated 3010 bytes in 71 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 27946|app: 0|req: 2/2] 125.121.39.215 () {52 vars in 1055 bytes} [Sun Sep 17 10:59:11 2017] POST /weixin/findTask/ => generated 3010 bytes in 42 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
Internal Server Error: /weixin/deleteTask/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "../weixin/views.py", line 35, in delete_task
    task = cursor.fetone()
AttributeError: 'DictCursor' object has no attribute 'fetone'
[pid: 27946|app: 0|req: 3/3] 125.121.39.215 () {44 vars in 849 bytes} [Sun Sep 17 10:59:13 2017] GET /weixin/deleteTask/?id= => generated 12422 bytes in 53 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from walry.ini
*** Starting uWSGI 2.0.15 (64bit) on [Sun Sep 17 19:01:26 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 28 June 2017 16:53:37
os: Linux-3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
nodename: izuf6e0xn290ligau0r66qz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mahl/projects/django/walry
detected binary path: /usr/bin/uwsgi
chdir() to /home/mahl/projects/django/walry/walry/
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8181 fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xf6df50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added ../ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xf6df50 pid: 28010 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 28010)
spawned uWSGI worker 1 (pid: 28015, cores: 1)
spawned uWSGI worker 2 (pid: 28016, cores: 1)
[pid: 28016|app: 0|req: 1/1] 125.121.39.215 () {52 vars in 1055 bytes} [Sun Sep 17 11:01:36 2017] POST /weixin/findTask/ => generated 3008 bytes in 61 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
Internal Server Error: /weixin/deleteTask/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "../weixin/views.py", line 35, in delete_task
    task = cursor.fetone()
AttributeError: 'DictCursor' object has no attribute 'fetone'
[pid: 28016|app: 0|req: 2/2] 125.121.39.215 () {44 vars in 2135 bytes} [Sun Sep 17 11:01:41 2017] GET /weixin/deleteTask/?id=function%20(a){var%20b,c,d,e=this[0];{if(arguments.length)return%20d=n.isFunction(a),this.each(function(c){var%20e;1===this.nodeType&&(e=d?a.call(this,c,n(this).val()):a,null==e?e=%22%22:%22number%22==typeof%20e?e+=%22%22:n.isArray(e)&&(e=n.map(e,function(a){return%20null==a?%22%22:a+%22%22})),b=n.valHooks[this.type]||n.valHooks[this.nodeName.toLowerCase()],b&&%22set%22in%20b&&void%200!==b.set(this,e,%22value%22)||(this.value=e))});if(e)return%20b=n.valHooks[e.type]||n.valHooks[e.nodeName.toLowerCase()],b&&%22get%22in%20b&&void%200!==(c=b.get(e,%22value%22))?c:(c=e.value,%22string%22==typeof%20c?c.replace(gb,%22%22):null==c?%22%22:c)}} => generated 14844 bytes in 46 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
[pid: 28016|app: 0|req: 3/3] 125.121.39.215 () {52 vars in 1055 bytes} [Sun Sep 17 11:01:51 2017] POST /weixin/findTask/ => generated 3008 bytes in 35 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
Internal Server Error: /weixin/deleteTask/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "../weixin/views.py", line 35, in delete_task
    task = cursor.fetone()
AttributeError: 'DictCursor' object has no attribute 'fetone'
[pid: 28016|app: 0|req: 4/4] 125.121.39.215 () {44 vars in 2135 bytes} [Sun Sep 17 11:03:08 2017] GET /weixin/deleteTask/?id=function%20(a){var%20b,c,d,e=this[0];{if(arguments.length)return%20d=n.isFunction(a),this.each(function(c){var%20e;1===this.nodeType&&(e=d?a.call(this,c,n(this).val()):a,null==e?e=%22%22:%22number%22==typeof%20e?e+=%22%22:n.isArray(e)&&(e=n.map(e,function(a){return%20null==a?%22%22:a+%22%22})),b=n.valHooks[this.type]||n.valHooks[this.nodeName.toLowerCase()],b&&%22set%22in%20b&&void%200!==b.set(this,e,%22value%22)||(this.value=e))});if(e)return%20b=n.valHooks[e.type]||n.valHooks[e.nodeName.toLowerCase()],b&&%22get%22in%20b&&void%200!==(c=b.get(e,%22value%22))?c:(c=e.value,%22string%22==typeof%20c?c.replace(gb,%22%22):null==c?%22%22:c)}} => generated 14844 bytes in 49 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from walry.ini
*** Starting uWSGI 2.0.15 (64bit) on [Sun Sep 17 19:04:43 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 28 June 2017 16:53:37
os: Linux-3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
nodename: izuf6e0xn290ligau0r66qz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mahl/projects/django/walry
detected binary path: /usr/bin/uwsgi
chdir() to /home/mahl/projects/django/walry/walry/
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8181 fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x2083f50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added ../ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x2083f50 pid: 28092 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 28092)
spawned uWSGI worker 1 (pid: 28097, cores: 1)
spawned uWSGI worker 2 (pid: 28098, cores: 1)
[pid: 28097|app: 0|req: 1/1] 125.121.39.215 () {52 vars in 1055 bytes} [Sun Sep 17 11:04:52 2017] POST /weixin/findTask/ => generated 3015 bytes in 61 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
Internal Server Error: /weixin/deleteTask/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "../weixin/views.py", line 35, in delete_task
    task = cursor.fetone()
AttributeError: 'DictCursor' object has no attribute 'fetone'
[pid: 28097|app: 0|req: 2/2] 125.121.39.215 () {44 vars in 849 bytes} [Sun Sep 17 11:04:56 2017] GET /weixin/deleteTask/?id= => generated 12422 bytes in 62 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from walry.ini
*** Starting uWSGI 2.0.15 (64bit) on [Sun Sep 17 19:06:15 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 28 June 2017 16:53:37
os: Linux-3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
nodename: izuf6e0xn290ligau0r66qz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mahl/projects/django/walry
detected binary path: /usr/bin/uwsgi
chdir() to /home/mahl/projects/django/walry/walry/
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8181 fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xe5df50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added ../ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xe5df50 pid: 28150 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 28150)
spawned uWSGI worker 1 (pid: 28155, cores: 1)
spawned uWSGI worker 2 (pid: 28156, cores: 1)
[pid: 28155|app: 0|req: 1/1] 125.121.39.215 () {52 vars in 1055 bytes} [Sun Sep 17 11:06:22 2017] POST /weixin/findTask/ => generated 3000 bytes in 64 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 28155|app: 0|req: 2/2] 125.121.39.215 () {52 vars in 1055 bytes} [Sun Sep 17 11:06:29 2017] POST /weixin/findTask/ => generated 3000 bytes in 30 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
Internal Server Error: /weixin/deleteTask/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "../weixin/views.py", line 35, in delete_task
    task = cursor.fetone()
AttributeError: 'DictCursor' object has no attribute 'fetone'
[pid: 28155|app: 0|req: 3/3] 125.121.39.215 () {44 vars in 849 bytes} [Sun Sep 17 11:06:31 2017] GET /weixin/deleteTask/?id= => generated 12422 bytes in 58 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from walry.ini
*** Starting uWSGI 2.0.15 (64bit) on [Sun Sep 17 19:10:04 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 28 June 2017 16:53:37
os: Linux-3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
nodename: izuf6e0xn290ligau0r66qz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mahl/projects/django/walry
detected binary path: /usr/bin/uwsgi
chdir() to /home/mahl/projects/django/walry/walry/
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8181 fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x26fdf50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added ../ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x26fdf50 pid: 28221 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 28221)
spawned uWSGI worker 1 (pid: 28226, cores: 1)
spawned uWSGI worker 2 (pid: 28227, cores: 1)
[pid: 28227|app: 0|req: 1/1] 125.121.39.215 () {52 vars in 1055 bytes} [Sun Sep 17 11:10:08 2017] POST /weixin/findTask/ => generated 3087 bytes in 74 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
Internal Server Error: /weixin/deleteTask/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "../weixin/views.py", line 35, in delete_task
    task = cursor.fetone()
AttributeError: 'DictCursor' object has no attribute 'fetone'
[pid: 28227|app: 0|req: 2/2] 125.121.39.215 () {44 vars in 849 bytes} [Sun Sep 17 11:10:11 2017] GET /weixin/deleteTask/?id= => generated 12422 bytes in 47 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
Internal Server Error: /weixin/deleteTask/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "../weixin/views.py", line 35, in delete_task
    task = cursor.fetone()
AttributeError: 'DictCursor' object has no attribute 'fetone'
[pid: 28227|app: 0|req: 3/3] 125.121.39.215 () {44 vars in 849 bytes} [Sun Sep 17 11:10:14 2017] GET /weixin/deleteTask/?id= => generated 12422 bytes in 55 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
[pid: 28227|app: 0|req: 4/4] 125.121.39.215 () {42 vars in 747 bytes} [Sun Sep 17 11:10:38 2017] GET /weixin/findTask/ => generated 1647 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 28227|app: 0|req: 5/5] 125.121.39.215 () {52 vars in 1041 bytes} [Sun Sep 17 11:10:47 2017] POST /weixin/findTask/ => generated 3087 bytes in 45 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
Internal Server Error: /weixin/deleteTask/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "../weixin/views.py", line 35, in delete_task
    task = cursor.fetone()
AttributeError: 'DictCursor' object has no attribute 'fetone'
[pid: 28227|app: 0|req: 6/6] 125.121.39.215 () {44 vars in 849 bytes} [Sun Sep 17 11:10:53 2017] GET /weixin/deleteTask/?id= => generated 12422 bytes in 45 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from walry.ini
*** Starting uWSGI 2.0.15 (64bit) on [Sun Sep 17 19:12:35 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 28 June 2017 16:53:37
os: Linux-3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
nodename: izuf6e0xn290ligau0r66qz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mahl/projects/django/walry
detected binary path: /usr/bin/uwsgi
chdir() to /home/mahl/projects/django/walry/walry/
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8181 fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1f08f50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added ../ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1f08f50 pid: 28290 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 28290)
spawned uWSGI worker 1 (pid: 28295, cores: 1)
spawned uWSGI worker 2 (pid: 28296, cores: 1)
[pid: 28296|app: 0|req: 1/1] 125.121.39.215 () {52 vars in 1055 bytes} [Sun Sep 17 11:12:46 2017] POST /weixin/findTask/ => generated 3132 bytes in 61 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 28296|app: 0|req: 2/2] 125.121.39.215 () {42 vars in 819 bytes} [Sun Sep 17 11:13:02 2017] GET /weixin/findTask/ => generated 1692 bytes in 3 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 28296|app: 0|req: 3/3] 125.121.39.215 () {44 vars in 850 bytes} [Sun Sep 17 11:13:14 2017] GET /weixin/findTask/ => generated 1692 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 28296|app: 0|req: 4/4] 125.121.39.215 () {52 vars in 1055 bytes} [Sun Sep 17 11:13:20 2017] POST /weixin/findTask/ => generated 3132 bytes in 35 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
Internal Server Error: /weixin/deleteTask/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "../weixin/views.py", line 35, in delete_task
    task = cursor.fetone()
AttributeError: 'DictCursor' object has no attribute 'fetone'
[pid: 28296|app: 0|req: 5/5] 125.121.39.215 () {44 vars in 849 bytes} [Sun Sep 17 11:13:24 2017] GET /weixin/deleteTask/?id= => generated 12422 bytes in 57 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
[pid: 28296|app: 0|req: 6/6] 125.121.39.215 () {38 vars in 643 bytes} [Sun Sep 17 11:13:46 2017] GET /weixin/findTask/ => generated 1692 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 28296|app: 0|req: 7/7] 125.121.39.215 () {48 vars in 937 bytes} [Sun Sep 17 11:14:06 2017] POST /weixin/findTask/ => generated 3132 bytes in 37 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 28296|app: 0|req: 8/8] 125.121.39.215 () {40 vars in 704 bytes} [Sun Sep 17 11:14:49 2017] GET /weixin/findTask/ => generated 1692 bytes in 3 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 28296|app: 0|req: 9/9] 125.121.39.215 () {52 vars in 1029 bytes} [Sun Sep 17 11:15:11 2017] POST /weixin/findTask/ => generated 3132 bytes in 36 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
Internal Server Error: /weixin/deleteTask/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "../weixin/views.py", line 35, in delete_task
    task = cursor.fetone()
AttributeError: 'DictCursor' object has no attribute 'fetone'
[pid: 28296|app: 0|req: 10/10] 125.121.39.215 () {44 vars in 823 bytes} [Sun Sep 17 11:15:26 2017] GET /weixin/deleteTask/?id= => generated 12396 bytes in 39 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from walry.ini
*** Starting uWSGI 2.0.15 (64bit) on [Sun Sep 17 19:17:19 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 28 June 2017 16:53:37
os: Linux-3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
nodename: izuf6e0xn290ligau0r66qz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mahl/projects/django/walry
detected binary path: /usr/bin/uwsgi
chdir() to /home/mahl/projects/django/walry/walry/
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8181 fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x111af50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added ../ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x111af50 pid: 28363 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 28363)
spawned uWSGI worker 1 (pid: 28368, cores: 1)
spawned uWSGI worker 2 (pid: 28369, cores: 1)
[pid: 28369|app: 0|req: 1/1] 125.121.39.215 () {52 vars in 1029 bytes} [Sun Sep 17 11:17:26 2017] POST /weixin/findTask/ => generated 3118 bytes in 68 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 28369|app: 0|req: 2/2] 125.121.39.215 () {52 vars in 1029 bytes} [Sun Sep 17 11:17:32 2017] POST /weixin/findTask/ => generated 3118 bytes in 46 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from walry.ini
*** Starting uWSGI 2.0.15 (64bit) on [Sun Sep 17 19:20:03 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 28 June 2017 16:53:37
os: Linux-3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
nodename: izuf6e0xn290ligau0r66qz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mahl/projects/django/walry
detected binary path: /usr/bin/uwsgi
chdir() to /home/mahl/projects/django/walry/walry/
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8181 fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xd8cf50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added ../ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xd8cf50 pid: 28428 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 28428)
spawned uWSGI worker 1 (pid: 28433, cores: 1)
spawned uWSGI worker 2 (pid: 28434, cores: 1)
[pid: 28434|app: 0|req: 1/1] 125.121.39.215 () {52 vars in 1029 bytes} [Sun Sep 17 11:20:09 2017] POST /weixin/findTask/ => generated 3157 bytes in 72 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from walry.ini
*** Starting uWSGI 2.0.15 (64bit) on [Sun Sep 17 19:25:28 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 28 June 2017 16:53:37
os: Linux-3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
nodename: izuf6e0xn290ligau0r66qz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mahl/projects/django/walry
detected binary path: /usr/bin/uwsgi
chdir() to /home/mahl/projects/django/walry/walry/
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8181 fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x14ccf50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added ../ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x14ccf50 pid: 28510 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 28510)
spawned uWSGI worker 1 (pid: 28515, cores: 1)
spawned uWSGI worker 2 (pid: 28516, cores: 1)
[pid: 28516|app: 0|req: 1/1] 125.121.39.215 () {52 vars in 1055 bytes} [Sun Sep 17 11:25:32 2017] POST /weixin/findTask/ => generated 3190 bytes in 57 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
Internal Server Error: /weixin/deleteTask/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "../weixin/views.py", line 35, in delete_task
    task = cursor.fetone()
AttributeError: 'DictCursor' object has no attribute 'fetone'
[pid: 28516|app: 0|req: 2/2] 125.121.39.215 () {44 vars in 863 bytes} [Sun Sep 17 11:25:34 2017] GET /weixin/deleteTask/?id=1347238 => generated 12450 bytes in 43 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
[pid: 28516|app: 0|req: 3/3] 125.121.39.215 () {52 vars in 1055 bytes} [Sun Sep 17 11:25:56 2017] POST /weixin/findTask/ => generated 3190 bytes in 30 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
Internal Server Error: /weixin/deleteTask/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "../weixin/views.py", line 35, in delete_task
    task = cursor.fetone()
AttributeError: 'DictCursor' object has no attribute 'fetone'
[pid: 28516|app: 0|req: 4/4] 125.121.39.215 () {44 vars in 863 bytes} [Sun Sep 17 11:26:01 2017] GET /weixin/deleteTask/?id=1347238 => generated 12450 bytes in 46 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
Internal Server Error: /weixin/deleteTask/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "../weixin/views.py", line 35, in delete_task
    task = cursor.fetone()
AttributeError: 'DictCursor' object has no attribute 'fetone'
[pid: 28516|app: 0|req: 5/5] 125.121.39.215 () {42 vars in 830 bytes} [Sun Sep 17 11:28:36 2017] GET /weixin/deleteTask/?id=1347238 => generated 59831 bytes in 85 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
Internal Server Error: /weixin/deleteTask/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "../weixin/views.py", line 35, in delete_task
    task = cursor.fetchone()
AttributeError: 'DictCursor' object has no attribute 'fetone'
[pid: 28516|app: 0|req: 6/6] 125.121.39.215 () {44 vars in 861 bytes} [Sun Sep 17 11:29:24 2017] GET /weixin/deleteTask/?id=1347238 => generated 59970 bytes in 80 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
Internal Server Error: /weixin/deleteTask/
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib64/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "../weixin/views.py", line 35, in delete_task
    task = cursor.fetchone()
AttributeError: 'DictCursor' object has no attribute 'fetone'
[pid: 28516|app: 0|req: 7/7] 125.121.39.215 () {44 vars in 861 bytes} [Sun Sep 17 11:29:27 2017] GET /weixin/deleteTask/?id=1347238 => generated 59970 bytes in 82 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from walry.ini
*** Starting uWSGI 2.0.15 (64bit) on [Sun Sep 17 19:29:32 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 28 June 2017 16:53:37
os: Linux-3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
nodename: izuf6e0xn290ligau0r66qz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mahl/projects/django/walry
detected binary path: /usr/bin/uwsgi
chdir() to /home/mahl/projects/django/walry/walry/
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8181 fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xfa2f50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added ../ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xfa2f50 pid: 28579 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 28579)
spawned uWSGI worker 1 (pid: 28584, cores: 1)
spawned uWSGI worker 2 (pid: 28585, cores: 1)
[pid: 28585|app: 0|req: 1/1] 125.121.39.215 () {44 vars in 861 bytes} [Sun Sep 17 11:29:36 2017] GET /weixin/deleteTask/?id=1347238 => generated 1939 bytes in 50 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 28585|app: 0|req: 2/2] 125.121.39.215 () {44 vars in 863 bytes} [Sun Sep 17 11:29:40 2017] GET /weixin/deleteTask/?id=1347238 => generated 1939 bytes in 33 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 28585|app: 0|req: 3/3] 115.239.138.179 () {34 vars in 504 bytes} [Sun Sep 17 18:47:39 2017] GET /weixin/findTask/ => generated 1650 bytes in 9 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
Not Found: /
[pid: 28585|app: 0|req: 4/4] 106.11.242.62 () {40 vars in 624 bytes} [Sun Sep 17 23:21:25 2017] GET / => generated 2018 bytes in 4 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[pid: 28585|app: 0|req: 5/5] 122.233.242.12 () {42 vars in 830 bytes} [Mon Sep 18 01:14:29 2017] GET /weixin/deleteTask/?id=1347238 => generated 1939 bytes in 37 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
[pid: 28585|app: 0|req: 6/6] 122.233.242.12 () {42 vars in 805 bytes} [Mon Sep 18 02:56:57 2017] GET /weixin/findTask/ => generated 1650 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 28585|app: 0|req: 7/7] 122.233.242.12 () {40 vars in 699 bytes} [Mon Sep 18 02:57:50 2017] GET /weixin/findTask/ => generated 1650 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 28585|app: 0|req: 8/8] 101.226.99.197 () {38 vars in 579 bytes} [Mon Sep 18 02:58:00 2017] GET /weixin/findTask => generated 0 bytes in 0 msecs (HTTP/1.1 301) 3 headers in 122 bytes (1 switches on core 0)
[pid: 28584|app: 0|req: 1/9] 101.226.99.197 () {40 vars in 634 bytes} [Mon Sep 18 02:58:00 2017] GET /weixin/findTask/ => generated 1650 bytes in 23 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 28585|app: 0|req: 9/10] 122.233.242.12 () {52 vars in 1018 bytes} [Mon Sep 18 02:58:57 2017] POST /weixin/findTask/ => generated 9563 bytes in 63 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from walry.ini
*** Starting uWSGI 2.0.15 (64bit) on [Mon Sep 18 11:36:55 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 28 June 2017 16:53:37
os: Linux-3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
nodename: izuf6e0xn290ligau0r66qz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mahl/projects/django/walry
detected binary path: /usr/bin/uwsgi
chdir() to /home/mahl/projects/django/walry/walry/
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8181 fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1ef5f50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added ../ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1ef5f50 pid: 2017 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 2017)
spawned uWSGI worker 1 (pid: 2022, cores: 1)
spawned uWSGI worker 2 (pid: 2023, cores: 1)
Not Found: /
[pid: 2022|app: 0|req: 1/1] 106.11.226.176 () {40 vars in 625 bytes} [Mon Sep 18 23:22:46 2017] GET / => generated 2018 bytes in 24 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[pid: 2022|app: 0|req: 2/2] 60.177.123.80 () {42 vars in 787 bytes} [Tue Sep 19 01:18:05 2017] GET /weixin/findTask/ => generated 1650 bytes in 8 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 2022|app: 0|req: 3/3] 101.226.233.149 () {36 vars in 567 bytes} [Wed Sep 20 02:12:05 2017] GET /weixin/findTask/ => generated 1650 bytes in 2 msecs (HTTP/1.0 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 2022|app: 0|req: 4/4] 218.108.153.26 () {42 vars in 804 bytes} [Wed Sep 20 02:12:16 2017] GET /weixin/findTask/ => generated 1650 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 278 bytes (1 switches on core 0)
[pid: 2022|app: 0|req: 5/5] 218.108.153.26 () {52 vars in 1040 bytes} [Wed Sep 20 02:12:27 2017] POST /weixin/findTask/ => generated 10505 bytes in 57 msecs (HTTP/1.1 200) 5 headers in 279 bytes (1 switches on core 0)
Not Found: /
[pid: 2022|app: 0|req: 6/6] 106.11.225.27 () {40 vars in 623 bytes} [Wed Sep 20 02:26:03 2017] GET / => generated 2018 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /
[pid: 2022|app: 0|req: 7/7] 106.11.226.48 () {40 vars in 624 bytes} [Thu Sep 21 00:00:58 2017] GET / => generated 2018 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[uWSGI] getting INI configuration from walry.ini
*** Starting uWSGI 2.0.15 (64bit) on [Thu Sep 21 15:27:38 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 28 June 2017 16:53:37
os: Linux-3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
nodename: izuf6e0xn290ligau0r66qz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mahl/projects/django/walry
detected binary path: /usr/bin/uwsgi
chdir() to /home/mahl/projects/django/walry/walry/
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8181 fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x932f50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added ../ to pythonpath.
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x932f50 pid: 4471 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 4471)
spawned uWSGI worker 1 (pid: 4476, cores: 1)
spawned uWSGI worker 2 (pid: 4477, cores: 1)
[uWSGI] getting INI configuration from walry.ini
*** Starting uWSGI 2.0.15 (64bit) on [Thu Sep 21 15:50:46 2017] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-11) on 28 June 2017 16:53:37
os: Linux-3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017
nodename: izuf6e0xn290ligau0r66qz
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/mahl/projects/django/walry
detected binary path: /usr/bin/uwsgi
chdir() to /home/mahl/projects/django/walry/walry/
your processes number limit is 4096
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8181 fd 3
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xb93f50
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 218304 bytes (213 KB) for 2 cores
*** Operational MODE: preforking ***
added ../ to pythonpath.
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0xb93f50 pid: 4617 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 4617)
spawned uWSGI worker 1 (pid: 4622, cores: 1)
spawned uWSGI worker 2 (pid: 4623, cores: 1)
Not Found: /
[pid: 4623|app: 0|req: 1/1] 106.11.227.174 () {40 vars in 625 bytes} [Thu Sep 21 23:56:34 2017] GET / => generated 2018 bytes in 20 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /
[pid: 4623|app: 0|req: 2/2] 140.205.201.18 () {38 vars in 659 bytes} [Fri Sep 22 20:12:52 2017] GET / => generated 2018 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /
[pid: 4623|app: 0|req: 3/3] 106.11.226.156 () {40 vars in 625 bytes} [Sat Sep 23 00:04:11 2017] GET / => generated 2018 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /
[pid: 4623|app: 0|req: 4/4] 106.11.242.22 () {40 vars in 624 bytes} [Sat Sep 23 23:52:48 2017] GET / => generated 2018 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /
[pid: 4623|app: 0|req: 5/5] 106.11.227.61 () {40 vars in 624 bytes} [Mon Sep 25 02:31:28 2017] GET / => generated 2018 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
